<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2017 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Popov
 * @package Popov_<package>
 * @author Serhii Popov <popow.sergiy@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<?= $this->partial('template/file-upload', [
    //'prefix' => $folder,
    'prefix' => 'student',
    //'loadJs' => (bool) ($i == $count),
    'loadJs' => true,
    #'permissionUploadFile' => $this->fields('uploadFile', ['mnemo' => $folder, 'page' => 'checkout-document/index']),
    #'permissionDeleteFile' => $this->fields('deleteFile', ['mnemo' => $folder, 'page' => 'checkout-document/index']),
    'permissionUploadFile' => true,
    'permissionDeleteFile' => true,
]) ?>
