<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2017 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Popov
 * @package Popov_<package>
 * @author Serhii Popov <popow.sergiy@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<div class="sidebar">

		<ul class="level-0">
			<?php if ($this->user()->isAdmin()) : ?>
			<li>
				<a href="/hello/first">First Hello</a>
				<ul class="level-1">
					<li><a href="/hello">Hello List</a></li>
				</ul>
			</li>
			<?php endif; ?>

			<li>
                <?php if ($this->user()->isAdmin()) : ?>
				<a href="/inquiry">Inquiries</a>
				<!--<ul class="level-1">
					<li><a href="/inquiry">List of Inquiries</a></li>
				</ul>-->
                <?php else: ?>
	                <?php $student = $this->module()->getEntityPlugin()
		                ->getObjectManager()
		                ->getRepository(\Popov\Student\Model\Student::class)
		                ->findOneBy(['user' => $this->user()->current()]) ?>
	                <a href="/inquiry/info/<?= $student->getInquiry()->getId() ?>">Inquiries</a>
                <?php endif; ?>

			</li>

		</ul>

</div>
